// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU9twouJTR-SF3HhkGrSmM1yGsfKKBu_w',
    appId: '1:989506535482:web:121adfb1c863e19423b503',
    messagingSenderId: '989506535482',
    projectId: 'chat-hoss',
    authDomain: 'chat-hoss.firebaseapp.com',
    storageBucket: 'chat-hoss.appspot.com',
    measurementId: 'G-ED1Y4YE5SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB04VvicaIwuyId-25dMx7aA2r7VeSh9Jc',
    appId: '1:989506535482:android:731fda6505be124723b503',
    messagingSenderId: '989506535482',
    projectId: 'chat-hoss',
    storageBucket: 'chat-hoss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQD1-hRHayqW2OskjpVIcT_nVnX7Igt1k',
    appId: '1:989506535482:ios:a4bd13ad8ef1459a23b503',
    messagingSenderId: '989506535482',
    projectId: 'chat-hoss',
    storageBucket: 'chat-hoss.appspot.com',
    iosClientId: '989506535482-h22r802sns3788m02ml61uogkg5a0jc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQD1-hRHayqW2OskjpVIcT_nVnX7Igt1k',
    appId: '1:989506535482:ios:a4bd13ad8ef1459a23b503',
    messagingSenderId: '989506535482',
    projectId: 'chat-hoss',
    storageBucket: 'chat-hoss.appspot.com',
    iosClientId: '989506535482-h22r802sns3788m02ml61uogkg5a0jc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
